# postgresql, redis
spring:
  datasource:
    base:
      url: jdbc:postgresql:localhost:5432/tablekiosk
      username: superuser
      password: tablekioskpassword
      driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: tablekiosk-core